version: '2'
services:
  jenkins:
    build: .
    container_name: 'jenkins'
    working_dir: '/root/opt'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
    driver: local
